# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: yoginet <marvin@le-101.fr>                 +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2018/03/15 10:39:49 by yoginet      #+#   ##    ##    #+#        #
#    Updated: 2018/03/15 10:40:33 by yoginet     ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

PHONY: all clean fclean re

NAME =		<ADD NAME>
CC = 		gcc
CC_FLAGS = 	-Wall -Werror -Wextra

N_INC =		<ADD>.h
N_SRCS = 	main.c\
			<ADD SRCS> \

P_SRCS = ./srcs/
P_INC = ./includes/
P_OBJ = ./obj/
P_LFT = libft/

I_INC = ./includes/
I_LFT = ./libft/includes/
L_LFT = -L./libft/ -lft

SRC = $(addprefix $(P_SRCS),$(N_SRCS))
OBJ = $(addprefix $(P_OBJ),$(OBJ_NAME))
INC = $(addprefix -I,$(I_INC) $(I_LFT))

OBJ_NAME = $(N_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	@make -C $(P_LFT)
	@$(CC) $(CC_FLAGS) -o $(NAME) $(OBJ) $(INC) $(L_LFT)

$(P_OBJ)%.o: $(P_SRCS)%.c
	@mkdir -p $(P_OBJ)
	@$(CC) $(CC_FLAGS) -o $@ -c $^ $(INC)

clean:
	@make -C $(P_LFT) clean
	@rm -rf $(P_OBJ)

fclean: clean
	@make -C $(P_LFT) fclean
	@rm -f $(NAME)

re: fclean all
